name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version-file: .python-version

      - name: Install Python Packages
        run: pip install -r requirements.txt & pip install -r requirements-dev.txt

      - name: Check Types
        run: mypy -p barbot

      - name: Run Tests
        run: python3 -m unittest discover
